# Generated by Django 5.0.4 on 2024-05-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(unique=True),
        ),
    ]
