# Generated by Django 5.0.3 on 2024-04-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApi', '0002_remove_channel_banneds_remove_channel_inviteds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
