# Generated by Django 5.0.4 on 2024-04-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApi', '0012_alter_tournament_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
        ),
    ]
