# Generated by Django 5.0.4 on 2024-05-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApi', '0015_alter_notification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatarPath',
            field=models.CharField(blank=True, default='avatars/default.png', max_length=100, null=True),
        ),
    ]
