services:
    db:
        image: postgres:16-bullseye
        container_name: db
        restart: always
        env_file:
            - .env
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "${POSTGRES_PORT}:${POSTGRES_PORT}"
        networks:
            - transcendence
        healthcheck:
            test: ["CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
            interval: 5s
            timeout: 5s
            retries: 5
        hostname: db

    backend:
        image: backend
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: backend
        restart: always
        env_file:
            - .env
        depends_on:
            db:
                condition: service_healthy
        ports:
            - "${BACKEND_PORT}:${BACKEND_PORT}"
        volumes:
            - ./ssl:/etc/backend/ssl
            - ./avatars:/home/backend/src/avatars
        networks:
            - transcendence
    websocket:
        image: websocket
        build: ./front_end/webSocket
        container_name: websocket
        env_file:
            - .env
        ports:
            - "5555:5555"
        networks:
            - transcendence
        restart: always

    webserver:
        image: webserver
        build: ./front_end/webServer
        container_name: webserver
        depends_on:
            - websocket
        env_file:
            - .env
        ports:
            - "5500:5500"
        volumes:
            - ./avatars:/webServer/web/img/avatars
        networks:
            - transcendence
        restart: always
    
    nginx-back:
        image: nginx
        build: ./nginx-back
        container_name: nginx-back
        depends_on:
            - backend
        env_file:
            - .env
        ports:
            - "443:443"
        volumes:
            - ./ssl:/etc/nginx/ssl
        networks:
            - transcendence
        restart: always

volumes:
    postgres-data:
        driver: local
    backend:
        driver: local
    nginx-back:
        driver: local
    webserver:
        driver: local

networks:
    transcendence:
        driver: bridge
