@url=https://localhost/api/v1

GET {{url}}/user/friendship
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0cmFuc2NlbmRlbmNlIiwidXNlcklkIjoyLCJpYXQiOjE3MTU2MTg5MTIsImV4cCI6MTcxNTcwNTMxMn0.aUbXFU8dLFV0cWzyixefe1bR0BBTfp24K0Q6cOsO65tap-De9w4xaA65h8b9GAY-tOq_NqrdETxRe-0TcWLcQHzSPclrl8-TRbFh6oXVzfVfpYPJ6yhHH2HkCqVNYvmjo7S-0D0pfNWxxR3tbLzXu7RlGo4Ryn75xqIO5vKu0id1QGszxOpQe187mW0zjDOLUKt9kKQk2j6eOgzbl1ZnRJ-yv1F6vMb18M4iJWQJRdQK_3opvQVQTXhRanXO9QhYBzak0a7vxKkgapFyKohSL6AiWHUm64QKS7oW_bTsnTHABQFQA8moX9solVaqs7LpAFWTsnDiW-EZWrEjVV2FjQ